# Number of pod replicas
replicaCount: 1

image:
  repository: alonaru/flask-aws-monitor
  tag: latest
  pullPolicy: Always

aws:
  # IMPORTANT: Create Kubernetes secret first with your AWS credentials:
  # kubectl create secret generic aws-credentials \
  #   --from-literal=AWS_ACCESS_KEY_ID=your_key \
  #   --from-literal=AWS_SECRET_ACCESS_KEY=your_secret
  secretName: aws-credentials
  
  # TODO: Update this to your AWS region where resources are located
  # Common values: us-east-1, us-west-2, eu-west-1, eu-central-1, ap-southeast-1
  defaultRegion: "eu-west-1"  # ⚠️ CHANGE THIS TO YOUR REGION

service:
  # Service type will be automatically set based on ingress.enabled:
  # - If ingress is enabled: ClusterIP
  # - If ingress is disabled: LoadBalancer
  port: 5001
  nodePort: 30080

ingress:
  # Set to true to enable Ingress (requires Ingress controller)
  # Set to false to use LoadBalancer service
  enabled: false
  className: nginx
  host: flask.local
  path: /
  annotations: {}
  tls:
    enabled: false
    secretName: flask-tls-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
